4.Tugas_Empat/config/routes.rb
Cobaimage3::Application.routes.draw do
 
  root 'posttings#index'
  resources :posttings

end

4.Tugas_Empat/app/models/postting.rb
class Postting < ActiveRecord::Base
  has_attached_file :picture, :styles => {:thumb => "200x100>"}, :default_url => "/Public/"
  
  validates :picture, :attachment_presence => true
  validates_with AttachmentPresenceValidator, :attributes => :picture
  
  #or use helper style validations
  validates_attachment_content_type :picture, 
                                      :content_type => /^image\/(png|gif|jpeg)/,
                                      :message => 'only (png/gif/jpeg) images'
  validates_attachment_size :picture,  :in => 0..1024.kilobytes      
end

4.Tugas_Empat/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

4.Tugas_Empat/app/controllers/posttings_controller.rb
class PosttingsController < ApplicationController
 
   def index
    @posttings = Postting.all
  end

  def new
    @postting = Postting.new
  end

  def destroy
    @postting = Postting.find(params[:id])
    @postting.destroy
    flash[:notice] = "Successfully destroyed painting."
    redirect_to action: 'index'
  end
  
  def edit
    @postting = Postting.find(params[:id])
  end

  def update
    @postting = Postting.find(params[:id])
    if @postting.update(postting_params)
      flash[:notice] = "Successfully updated"
      redirect_to action: 'index'
    else
      render :action => 'edit'
    end
  end

  def create
    @postting = Postting.new(postting_params)
    if @postting.save
      redirect_to action: 'index', notice: 'User was successfully created.'
    else
      render action: 'new', alert: 'User could not be created' 
    end
  end

  private
    def postting_params
      params.require(:postting).permit(:title, :content, :picture)
    end
end

4.Tugas_Empat/app/helpers/application_helper.rb
module ApplicationHelper
end

4.Tugas_Empat/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cobaimage3</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

4.Tugas_Empat/app/views/posttings/_slider.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
  <style>
  .carousel-inner > .item > img,
  .carousel-inner > .item > a > img {
      width: 70%;
      margin: auto;
  }
  </style>
</head>
<body>

<div class="container">
  <br>
  <div id="myCarousel" class="carousel slide" data-ride="carousel">

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
      <div class="item">
        <%= image_tag(postting.pictue.url()) %>
      </div>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>

</body>
</html>

4.Tugas_Empat/app/views/posttings/edit.html.erb
<h1>Posttings#edit</h1>
<p>Find me in app/views/posttings/edit.html.erb</p>

<%= form_for(@postting) do |f| %>
  <% if @postting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@postting.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @postting.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <!-- Upload your attachments via a simple file_fields in the form -->
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content, cols: 20, rows: 10  %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.file_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', posttings_path %>

4.Tugas_Empat/app/views/posttings/index.html.erb
<h1>Posttings#index</h1>
<p>Find me in app/views/posttings/index.html.erb</p>

<%= link_to 'New Postting', new_postting_path %>
<h1>Listing POSTTING</h1>
	<% @posttings.each do |postting| %>
		<div class="postting"><%=link_to image_tag(postting.picture.url(:thumb)), postting.picture.url(:original), class: "fancybox"%>
		<div class="name"><%= postting.title %>
        <div class="content"><%= postting.content %>
        <div class="actions"><%= link_to "edit", edit_postting_path(postting) %> || <%= link_to "remove", postting, :confirm => 'Are you sure?', :method => :delete %>
        	</div>
        	</div>
        	</div>
        	</div>
    <% end %>

4.Tugas_Empat/app/views/posttings/new.html.erb
<h1>Posttings#new</h1>
<p>Find me in app/views/posttings/new.html.erb</p>

<%= form_for(@postting) do |f| %>
  <% if @postting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@postting.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @postting.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <!-- Upload your attachments via a simple file_fields in the form -->
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content, cols: 20, rows: 10  %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.file_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', posttings_path %>