3.Tugas_tiga/config/routes.rb
TugasTiga::Application.routes.draw do
  get "portfolio/home"
  get "portfolio/profil"
  get "portfolio/contact"
  
   root :to => "portfolio#home"
   resources :portfolio

end

3.Tugas_tiga/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

3.Tugas_tiga/app/controllers/portfolio_controller.rb
class PortfolioController < ApplicationController
  def home
  end

  def profil
  end

  def contact
  end
end

3.Tugas_tiga/app/helpers/application_helper.rb
module ApplicationHelper
end

3.Tugas_tiga/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TugasTiga</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

3.Tugas_tiga/app/views/portfolio/_navigationbar.html.erb
 <div class="navbar navbar-fixed-top navbar-default" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"/>
            <span class="icon-bar"/>
            <span class="icon-bar"/>
          </button>
          <a href=”#” class = "navbar-brand">Training Bootstrap</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home", portfolio_home_path() %></li>
            <li><%= link_to "Profil", portfolio_profil_path() %></a></li>
            <li><%= link_to "Contact", portfolio_contact_path() %></a></li>
          </ul>
        </div>  
      </div>
    </div>

3.Tugas_tiga/app/views/portfolio/contact.html.erb
<p><%= render 'navigationbar' %></p>
<br />
<br />
<br />
<!-- Bagian Content -->
<div class="container clearfix">
	<div class="row row-offcanvas row-offcanvas-left ">
	<!--Bagian Kiri-->
		<div class="col-xs-12 col-sm-3 side pull-left sidebar-offcanvas" id="sidebar" role="navigation">
			<div class="list-group">
				<h1> Riku Kiranatama </h1>
			</div>
				<%= image_tag("1.jpg", class: "img-circle", height: '100', width: '100')%>
		</div>
	<!--Bagian Kanan-->
		<div id="main-content" class="col-xs-12 col-sm-9 main pull-right">
			<form class="form-horizontal" role="form">
				<div class="form-group">
						<label class="control-label col-sm-1" for="pwd">Email:</label>
					<div class="col-sm-10">          
						<input type="password" class="form-control" id="pwd" placeholder="Enter Email">
					</div>
				</div>
				<div class="form-group">
						<label class="control-label col-sm-1" for="pwd">Message:</label>
					<div class="col-sm-10">
						<textarea class="form-control" rows="8" id="Message" placeholder="Enter Message"></textarea>
					</div>
				</div>
		</div>
				<div class="form-group">        
					<div class="col-sm-offset-3 col-sm-8">
						<button type="submit" class="btn btn-default">Submit</button>
					</div>
				</div>
			</form>
	</div>
</div>

3.Tugas_tiga/app/views/portfolio/home.html.erb
<%= render 'navigationbar' %>
<br />
<br />
<br />
	<div class="container">
		<div id="myCarousel" class="carousel slide" data-ride="carousel">
		<!-- Indicators -->
			<ol class="carousel-indicators">
      			<li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      			<li data-target="#myCarousel" data-slide-to="1"></li>
    		</ol>
    	<!-- Wrapper for slides -->
    	<div class="carousel-inner" role="listbox">
      		<div class="item active" align="center">
        		<%= image_tag("1.jpg", :width => "600" , :height => "500" ) %>
        		<div class="carousel-caption" >
          			<h3>Gang Di Kota Bandung</h3>
        		</div>
      		</div>
			<div class="item" align="center">
        		<%= image_tag("2.jpg", :width => "600" , :height => "500" ) %>
        		<div class="carousel-caption">
          			<h3>Bandung Kota Di Gang</h3>
        		</div>
      		</div>  
    	</div>
    	<!-- Left and right controls -->
    	<a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
      		<span aria-hidden="true"></span>
      		<span class="sr-only">Previous</span>
    	</a>
    	<a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
      		<span aria-hidden="true"> </span>
      		<span class="sr-only">Next</span>
    	</a>
  		</div>
	</div>
	<div class="col-xs-15 col-sm-3 side pull-right sidebar-offcanvas" id="sidebar" role="navigation">
		<div class="list-group">
	            <h5>Facebook:riku@gmail.com</h5>
	            <h5>Twiter:riku@mail.com</h5>
	            <h5>Telpon:022-232392</h5>
	            <h5>Alamat:Jl Harapan Bangsano 23,Bandung,Indonesia</h5>
        </div>
    </div>       
	<div class="col-xs-15 col-sm-4 side pull-left sidebar-offcanvas" id="sidebar" role="navigation">
        <div class="list-group">
	        	<h4>Hello saya Riku dan saya ini akan lulus dari kuliah,
	            	salam kenal ya. Berikut contoh hasil desaign grafik yang saya buat :)</h4>
        </div>
    </div>
    </div>
</div>
</div>

3.Tugas_tiga/app/views/portfolio/profil.html.erb
<p><%= render 'navigationbar' %></p>
<br />
<br />
<br />
<!-- Bagian Content -->
<div class="container clearfix">
	<div class="row row-offcanvas row-offcanvas-left ">
	<!--Bagian Kiri-->
		<div class="col-xs-12 col-sm-3 side pull-left sidebar-offcanvas" id="sidebar" role="navigation">
			<div class="list-group">
				<h1> Riku Kiranatama </h1>
			</div>
				<%= image_tag("1.jpg", class: "img-circle", height: '100', width: '100')%>
		</div>
	<!--Bagian Kanan-->
		<div id="main-content" class="col-xs-12 col-sm-9 main pull-right">
			<div class="panel-body">
				<table  class="table table-bordered table-hover table-striped display" >
					<tr>
						<td>Nama</td>
						<td>Riku Kiranatama</td>
					</tr>
					<tr>
						<td>Tempat, Tanggal Lahir</td>
						<td>Bandung, 7 Oktober 1999</td>
					</tr>
					<tr>
						<td>Jenis Kelamin</td>
						<td>Pria</td>
					</tr>
					<tr>
						<td>Alamat Domisili</td>
						<td>Jl.Soekarno Hatta no. 104</td>
					</tr>
				</table>
			</div>
		</div>
	</div>
</div>